#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new \Symfony\Component\Console\Application('Spline Console App', '1.0');
$app->add(new \Spline\FindReplaceCommand());
$app->add(new \Spline\ResizeImageCommand());

$app->run();
