#!/usr/bin/env php
<?php

use Ecology\FindReplaceCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Ecology Console App', '1.0');

$app->add(new FindReplaceCommand);

$app->run();